### ISSUE TITLE
Integrate Personalized Recommendations

### ISSUE THREAD

**Issue by VinhDuyLe** [web103-codepath-g25/melodymix#3]
**Description**: 

- Implement the algorithm to analyze user history and suggest songs.

**Tasks**:

- [ ] Write the recommendation algorithm.
- [ ] Connect the algorithm to the backend.
- [ ] Display results on the user dashboard.

**Comment by VinhDuyLe** [comment]
Here is the video to show the result of song recommendation algorithm

https://imgur.com/a/5whXQ3v
