### ISSUE TITLE
User can add song, filter

### ISSUE THREAD

**Issue by VinhDuyLe** [web103-codepath-g25/melodymix#4]
**Tasks:
- [x] Create the join table in PostgreSQL.
- [x] Implement backend routes for adding/removing song.
- [x] Update the frontend to allow filter song.

**Comment by VinhDuyLe** [comment]
https://github.com/user-attachments/assets/9503483e-3812-4c84-971a-ed1604c583b9

**Comment by VinhDuyLe** [comment]
API Testing all fetures
https://vimeo.com/1031834940
